language: "zh"

pipeline:
- name: "MitieNLP"
  model: "data/cn/total_word_feature_extractor_zh.dat"
  num_threads: 16
- name: "JiebaTokenizer"
  dictionary_path: "jieba_userdict"
- name: "ner_mitie"
- name: "ner_synonyms"
- name: "intent_featurizer_mitie"
- name: "intent_classifier_sklearn"
